#!/usr/bin/env sh
# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKER_REPO: the name of the Docker repository being built.
# DOCKERFILE_PATH: the dockerfile currently being built.
# DOCKER_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)
echo "------ HOOK START - pre-build -------"
printenv

echo "SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "COMMIT_MSG     : $COMMIT_MSG"
echo "DOCKER_REPO    : $DOCKER_REPO"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "DOCKER_TAG     : $DOCKER_TAG"
echo "IMAGE_NAME     : $IMAGE_NAME"

echo "------ HOOK END - pre-build -------"